services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: linh
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080